name: Bitch Macs

on:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        os: macos-latest
        env:
          -
            TARGET: avr
            PACKAGES: binutils gcc avr-libc
          -
            TARGET: avr
            PACKAGES: gdb avarice simulavr avrdude
          -
            TARGET: ia16-elf
            PACKAGES: binutils gcc newlib

    steps:
      - uses: actions/checkout@v4

      - name: Clear brew package cache
        run: |
          rm -rf $(brew --cache)

      - name: Cache brew package cache
        uses: actions/cache@v4
        with:
          path: ~/Library/Caches/Homebrew
          key: testbuild-brew-cache-${{ github.sha }}
          restore-keys: |
            testbuild-brew-cache-

      - name: Install dependencies (macos)
        continue-on-error: true
        run: |
          brew update || :
          brew install --formula bash curl make texinfo gzip xz dos2unix libtool cmake help2man nasm s-lang ccache gnu-sed libobstack

      - name: Setup environment (macos)
        if: contains(matrix.os, 'macos')
        run: |
          mkdir -p $HOME/.ccache
          echo "CCACHE_DIR=$HOME/.ccache" >> $GITHUB_ENV
          echo "$(brew --prefix)/opt/ccache/libexec" >> $GITHUB_PATH
          echo "$(brew --prefix gnu-sed)/libexec/gnubin" >> $GITHUB_PATH
          echo CFLAGS="$CFLAGS -Wno-error=deprecated-declarations -Wno-error=mismatched-tags -Wno-implicit-function-declaration -fcommon" >> $GITHUB_ENV
          echo CXXFLAGS="$CXXFLAGS -Wno-error=deprecated-declarations -Wno-error=mismatched-tags" >> $GITHUB_ENV

      - name: Cache sources
        uses: actions/cache@v4
        with:
          path: download
          key: testbuild-sources-macOS-${{ matrix.env.TARGET }}-${{ matrix.env.PACKAGES }}-${{ github.sha }}
          restore-keys: |
            testbuild-sources-macOS-${{ matrix.env.TARGET }}-${{ matrix.env.PACKAGES }}-

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: testbuild-ccache-macOS-${{ matrix.env.TARGET }}-${{ matrix.env.PACKAGES }}-${{ github.sha }}
          restore-keys: |
            testbuild-ccache-macOS-${{ matrix.env.TARGET }}-${{ matrix.env.PACKAGES }}-

      - name: Download sources
        env:
          TARGET: ${{ matrix.env.TARGET }}
          PACKAGES: ${{ matrix.env.PACKAGES }}
        run: ./script/select-script.sh --only-download

      - name: Build
        env:
          TARGET: ${{ matrix.env.TARGET }}
        run: ./script/select-script.sh --no-download --prefix=${{ github.workspace }}-${{ github.sha }} ${{ matrix.env.PACKAGES }}

      - name: Clear and pack git sources before caching
        run: |
          find download/*/* ! -wholename '*/.git/*' -delete || true
          cd download
          for DIR in */; do
            DIR=${DIR%/}
            tar -c -f $DIR-git.tar $DIR
          done
          rm -rf */
